source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.4'

gem 'pg'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.2'
gem 'bootstrap-sass', '~> 3.1.1'
gem 'font-awesome-rails', '~> 4.0.3.1'
gem 'haml', '~> 4.0.5'
gem 'haml-rails', '~> 0.5.3'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
#gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require:false
end

group :development do
  gem 'spring'
  gem 'mina'
  gem 'mina-rsync', '~> 1.1.0', :require => false
  # gem 'capistrano'
  # gem 'capistrano-rvm'
  # gem 'capistrano-rails', '~> 1.1'
  # gem 'capistrano-bundler', '~> 1.1.2'
  gem 'debugger'
end



gem 'settingslogic', '~> 2.0.9'
gem 'sanitize', '~> 2.1.0'
gem 'devise', '~> 3.2.3'
gem 'omniauth', '~> 1.2.1'
gem 'omniauth-ldap', '~> 1.0.4'
gem 'cancancan', '~> 1.7'
gem 'kaminari', '~> 0.15.1'
gem 'bunny', '~> 1.2.2'
gem 'iconv', '~> 1.0.4'
gem 'select2-rails'
gem 'puma', '~> 2.9.0'


# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]


